language: ruby
rvm:
  - 2.2
notifications:
  slack:
    rooms:
      secure: mUqRm5ojVIyICeVdY+SA+FME+TkZDytGpQeaUEd0GsCxJBKWr3XhzWts5vSoz1evPJnYf8nW26PJKw9b1C8hlSf/45OJ3pRt01WJDnjfxdbCx8r7Er5/bw6JoFSdUd85RQEPGkqzB/6ojypVeA9pra0adicdsmCml8FY7ARLbNF87J/2hhWcw395ijecgUvT/BCEvUkzJB0sLRe20/cRilIqgNRgLaQitk+bErSDOQR3Q4J3gxFC5UcmgCr+vCgZuiihfDc7uWA7UE0HLybFwQTj1ZLfpVuyu1vTTmEBPyv8FVfHERQCZWV5t9i2JcBZubPO3eqArm0epjmMb1SKa0DKQwTpiboIRLLz96PSozwrkA4p/6+2TVTjzz1/UuJREBAudKovbPIi0MOzDEvSVo4OVbHHl6MfWgwSSRgSr6yG1xYXfINKB9sI9EHxsXkYyVPfz8kxQGk/qlW/Tz2+Z13GcU0/K5mnS3G1TzcofthLi2uOQRyKDsMlpkXIP2MBlJTCOwLqsyqABxZiHBAHxLwc0OAVe15UDoa9n+ELL+z9AC/s0NnYiCVt95s5KyE9xcUNr7P7JF1tFH4qcSaZ3vpB8EXh07NKi8ihKOiGxZBlX4uw50UQFgZFJWDN6rhHAgy0GoEKoclPyWyB6jIEHUICHKMJvlz7SIkiVkSeBpE=
